apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "chatoverlay.backendName" . }}"
  labels:
    {{- include "chatoverlay.backendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "chatoverlay.backendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chatoverlay.backendLabels" . | nindent 8 }}
    spec:
      containers:
        - name: "{{ include "chatoverlay.backendName" . }}"
          image: "{{ .Values.backendImage.repository }}:{{ .Values.backendImage.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.backendService.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
          - secretRef: 
              {{- $backendName := include "chatoverlay.backendName" . }}
              name: {{ .Values.backend.secretName | default $backendName | quote }}