apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatoverlay.backendName" . }}
  labels:
    {{- include "chatoverlay.backendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.backendService.type }}
  ports:
    - port: {{ .Values.backendService.port }}
      targetPort: {{ .Values.backendService.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "chatoverlay.backendSelectorLabels" . | nindent 4 }}
