{{- if not .Values.frontend.skip -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "chatoverlay.frontendName" . }}"
  labels:
    {{- include "chatoverlay.frontendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "chatoverlay.frontendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chatoverlay.frontendLabels" . | nindent 8 }}
    spec:
      containers:
        - name: "{{ include "chatoverlay.frontendName" . }}"
          image: "{{ .Values.frontendImage.repository }}:{{ .Values.frontendImage.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.frontendService.port }}
              protocol: TCP
          {{- with .Values.frontendLivenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontendReadinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
          - secretRef:
              {{- $frontendName := include "chatoverlay.frontendName" . }}
              name: {{ .Values.frontend.secretName | default $frontendName | quote }}
{{- end -}}              