name: smart-build.yml
on: 
  push:
    branches:
      - "testing"

jobs:      
  set_variables: 
    name: Get info from commit message
    runs-on: docker-build-etmbp
    permissions:
      contents: read
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Get frontend version
        run: echo ${{ github.event.head_commit.message }} | grep -oE "\[fev\:[0-9]+\.[0-9]+\.[0-9]+\]" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+"