name: smart-build.yml
on: 
  push:
    branches:
      - "testing"

jobs:      
  set_variables: 
    name: Get info from commit message
    runs-on: docker-build-etmbp
    permissions:
      contents: read
    outputs:
      frontend_version: ${{ steps.versions.outputs.frontend_version }}
      backend_version: ${{ steps.versions.outputs.backend_version }}
    steps:
      - name: Get frontend version
        id: versions
        run: |
          export FE_VER=$(echo ${{ github.event.head_commit.message }} | grep -oE "\[fev\:[0-9]+\.[0-9]+\.[0-9]+\]" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+")
          echo "frontend_version=$FE_VER" >> $GITHUB_ENV
          echo "frontend_version=$FE_VER" >> $GITHUB_OUTPUT
          export BE_VER=$(echo ${{ github.event.head_commit.message }} | grep -oE "\[bev\:[0-9]+\.[0-9]+\.[0-9]+\]" | grep -oE "[0-9]+\.[0-9]+\.[0-9]+")
          echo "backend_version=$BE_VER" >> $GITHUB_ENV
          echo "backend_version=$BE_VER" >> $GITHUB_OUTPUT
      - name: Show result
        run: |
          echo "Frontend version: $frontend_version"
          echo "Backend version: $backend_version"
  build_frontend_image:
    needs: set_variables
    if: ${{  needs.set_variables.outputs.frontend_version }}
    name: Build frontend image
    runs-on: docker-build-etmbp
    permissions:
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: zelixplore/chatoverlay-frontend
          tags: |
            type=raw,${{ needs.set_variables.outputs.frontend_version }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  push_backend_to_registry:
    name: Push backend image to Docker Hub
    needs: set_variables
    if: ${{  needs.set_variables.outputs.backend_version }}
    runs-on: docker-build-etmbp
    permissions:
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: zelixplore/chatoverlay-backend
          tags: |
            type=raw,${{ needs.set_variables.outputs.backend_version }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}